// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVr4ylxixMk4_mSSxCUWMAHIQlPScskg',
    appId: '1:357759406743:web:224f8fc10878e9ab158fd2',
    messagingSenderId: '357759406743',
    projectId: 'basicprojectlab-1',
    authDomain: 'basicprojectlab-1.firebaseapp.com',
    storageBucket: 'basicprojectlab-1.firebasestorage.app',
    measurementId: 'G-JWNR8LY4QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUHy5HsRGzMsOrZUa5qVfd4C45AL34iY',
    appId: '1:357759406743:android:a76285b47534164a158fd2',
    messagingSenderId: '357759406743',
    projectId: 'basicprojectlab-1',
    storageBucket: 'basicprojectlab-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9txeTXyYi1Yahk0eNtqqB8j6WfRqSZx8',
    appId: '1:357759406743:ios:a24fe09c616338e4158fd2',
    messagingSenderId: '357759406743',
    projectId: 'basicprojectlab-1',
    storageBucket: 'basicprojectlab-1.firebasestorage.app',
    iosBundleId: 'com.example.basicprojectlab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9txeTXyYi1Yahk0eNtqqB8j6WfRqSZx8',
    appId: '1:357759406743:ios:a24fe09c616338e4158fd2',
    messagingSenderId: '357759406743',
    projectId: 'basicprojectlab-1',
    storageBucket: 'basicprojectlab-1.firebasestorage.app',
    iosBundleId: 'com.example.basicprojectlab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVr4ylxixMk4_mSSxCUWMAHIQlPScskg',
    appId: '1:357759406743:web:5637d3dd6c7eebdb158fd2',
    messagingSenderId: '357759406743',
    projectId: 'basicprojectlab-1',
    authDomain: 'basicprojectlab-1.firebaseapp.com',
    storageBucket: 'basicprojectlab-1.firebasestorage.app',
    measurementId: 'G-99V2202SH9',
  );
}
